apiVersion: apps/v1
kind: Deployment
metadata:
  name: junction-deployment
  namespace: kong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: junction-service
  template:
    metadata:
      labels:
        app: junction-service
    spec:
      containers:
        - name: junction-service-app
          image: xenos.azurecr.io/junction-service:${{ github.sha }}
          ports:
            - containerPort: 8055
         
---
apiVersion: v1
kind: Service
metadata:
  name: service-junction
  namespace: kong
spec:
  selector:
    app: junction-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8055